const Titles = [
  "Aharen-san wa Hakarenai",
  "Akame ga Kill!",
  "Akatsuki no Yona",
  "Ansatsu Kyoushitsu",
  "Ao Haru Ride",
  "Ao No Exorcist",
  "Attack On Titans",
  "Bakemonogatari",
  "Bakuman",
  "Berserk",
  "Black Clover",
  "Bleach",
  "Blue Lock",
  "Boku No Hero Academia",
  "Boku dake ga Inai Machi",
  "Boruto NNG",
  "Btooom!",
  "Bungou Stray Dogs",
  "Burn The Witch",
  "Chainsaw Man",
  "Classroom of the Elite: Year 1",
  "Classroom of the Elite: Year 2",
  "Dead Tube",
  "Deadman Wonderland",
  "Death Note",
  "Death Note Tokubetsu Yomikiri",
  "Death Note Tokubetsu-hen",
  "Detective Conan",
  "Devils Line",
  "Devils Line II [Gyakushuu]",
  "Dr. Stone Reboot: Byakuya",
  "Dr: Stone",
  "Dragon Ball",
  "Dragon Ball Super",
  "Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka",
  "Durarara!!",
  "Durarara!! SH",
  "Edens Zero",
  "Fairy Tail",
  "Fairy Tail 100 Years Quest",
  "Fairy Tail Zero",
  "Fire Force",
  "Fire Punch",
  "Fullmetal Alchemist",
  "Gleipnir",
  "Goblin Slayer",
  "Goblin Slayer Gaiden 2: Tsubanari no Daikatana",
  "Goblin Slayer Gaiden: Year One",
  "Golden Kamuy",
  "Haikyuu!!",
  "High-School DxD",
  "Highschool of the Dead",
  "Horimiya",
  "Hunter x Hunter",
  "I Sold My Life For Ten Thousand Yen Per Year",
  "Ijimeru Yabai Yatsu",
  "Ijiranaide, Nagatoro-san",
  "Isekai Maou to Shoukan Shoujo no Dorei Majutsu",
  "Jibaku Shounen Hanako-kun",
  "Jujutsu Kaisen",
  "Jujutsu Kaisen 0",
  "Kaguya-sama: Love is War",
  "Kaiju No. 8",
  "Kakegurui",
  "Kakegurui Midari",
  "Kakegurui Twin",
  "Kanojo, Okarishimasu",
  "Kawaii dake ja Nai Shikimori-san",
  "Kawaikereba Hentai demo Suki ni Natte Kuremasuka",
  "Kimetsu No Yaiba",
  "Kimi no Na wa",
  "Kingdom",
  "Kiseijuu",
  "Koe no Katachi",
  "Koi to Uso",
  "Kokou no Hito",
  "Komi Can't Communicate",
  "Kono Subarashii Sekai ni Shukufuku wo!",
  "Kuroko No Basket",
  "Kuzumi-Kun Cant You Read the Room",
  "Made in Abyss",
  "Magi",
  "Mairimashita, Senpai",
  "Masamune-kun no Revenge",
  "Mashle",
  "Mirai Nikki",
  "Mob Psycho 100",
  "Monster",
  "Mushoku Tensei: Isekai Ittara Honki Dasu",
  "Nanatsu no Taizai",
  "Naruto",
  "Naruto: Shippuuden",
  "New Game!",
  "Nisekoi",
  "No Game No Life",
  "Noragami",
  "One Piece",
  "One Punch Man",
  "Orange",
  "Overlord",
  "Perfect World",
  "Platinum End",
  "Prison School",
  "Pumpkin Night",
  "Re:Zero kara Hajimeru Isekai Seikatsu",
  "Record Of Ragnarok",
  "Redo of Healer",
  "Sakamoto Days",
  "Samurai 8 Hachimaruden",
  "Shigatsu wa Kimi no Uso",
  "Shokugeki no Souma",
  "Slam Dunk",
  "Sono Bisque Doll wa Koi wo Suru",
  "Soul Eater",
  "Spy X Family",
  "Sun-Ken Rock",
  "Sword Art Online",
  "Tate No Yuusha No Nariagari",
  "Tensei shitara Slime Datta Ken",
  "The Four Knights of Apocalypse",
  "The Promised Neverland",
  "Todai Revengers",
  "Tokyo Ghoul",
  "Tokyo Ghoul:re",
  "Tokyo Revengers",
  "Tokyo Revengers: Letter from Keisuke Baji",
  "Tomo-chan wa Onnanoko!",
  "Tonikaku Kawaii",
  "Tsuujou Kougeki ga Zentai Kougeki de Ni-kai Kougeki no Okaasan wa Suki desu ka?",
  "Vagabond",
  "Vinland Saga",
  "We Never Learn",
  "Wotaku ni Koi wa Muzukashii",
  "Yahari Ore no Seishun Love Comedy wa Machigatteiru.",
  "Yamada-kun to 7-nin no Majo",
  "Youjo Senki",
  "Zetman",
  "",
  "Mahoutsukai no Yome",
  "Otonari no Tenshi-sama ni Itsunomanika Dame Ningen ni Sareteita Ken",
  "",
  "",
  "",
  "",
  "",
  "",
  "Fate/stay night",
  "Fate/hollow ataraxia",
  "Fate/Zero",
  "",
  "Fate/kaleid liner Prisma☆Illya",
  "Fate/kaleid liner Prisma☆Illya 2wei!",
  "Fate/kaleid liner Prisma☆Illya 3rei!!",
  "",
  "Fate/strange fake",
  "Fate/Apocrypha",
  "",
  "Fate/EXTRA",
  "Fate/EXTRA CCC",
  "Fate/EXTRA CCC FoxTail",
  "",
  "Fate/Prototype: Fragments of Sky Silver",
  "Lord El-Melloi II's Case Files",
  "Garden of Avalon",
  "Fate/Labyrinth",
  "Fate/stay night: Heaven's Feel",
  "Today's Menu for Emiya Family",
  ""
]

module.exports = { Titles }